%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callback Function of Module Control %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Version: v1.0 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Date: 2022/12/07 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Li.Ang %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Email: li.ang@cidi.ai %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SimulinkModel = "Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/" + ...
                "MODULE::Control";
FLAG_LON_CONTROLLER_ = get_param(SimulinkModel,'FLAG_LON_CONTROLLER_');
FLAG_LAT_CONTROLLER_ = get_param(SimulinkModel,'FLAG_LAT_CONTROLLER_');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Set Simulation Mode %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch FLAG_LAT_CONTROLLER_
    case "Manual"
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/Manual_Controller'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/LQR_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MRAC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPPI_Based_Controller'],'Commented','on');
    case "LQR Based Algorithms"
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/Manual_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/LQR_Based_Controller'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MRAC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPPI_Based_Controller'],'Commented','on');
    case "MPC Based Algorithms"
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/Manual_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/LQR_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPC_Based_Controller'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MRAC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPPI_Based_Controller'],'Commented','on');
    case "MRAC Based Algorithms"
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/Manual_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/LQR_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MRAC_Based_Controller'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPPI_Based_Controller'],'Commented','on');
    case "MPPI Based Algorithms"
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/Manual_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/LQR_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MRAC_Based_Controller'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40b/MODULE::AutoPilot/' ...
            'MODULE::Control/MODULE::Control::Controller/' ...
            'Lat_Controller/MPPI_Based_Controller'],'Commented','off');
end