%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callback Function of Module Simulation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Version: v1.0 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Date: 2022/12/01 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Li.Ang %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Email: li.ang@cidi.ai %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SimulinkModel = "Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation";
FLAG_MODE_ = get_param(SimulinkModel,'FLAG_MODE_');
FLAG_ENG_LAG_ = get_param(SimulinkModel,'FLAG_ENG_LAG_');
FLAG_MTR_LAG_ = get_param(SimulinkModel,'FLAG_MTR_LAG_');
FLAG_BRK_LAG_ = get_param(SimulinkModel,'FLAG_BRK_LAG_');
FLAG_STR_LAG_ = get_param(SimulinkModel,'FLAG_STR_LAG_');
FLAG_ENG_DELAY_ = get_param(SimulinkModel,'FLAG_ENG_DELAY_');
FLAG_MTR_DELAY_ = get_param(SimulinkModel,'FLAG_MTR_DELAY_');
FLAG_BRK_DELAY_ = get_param(SimulinkModel,'FLAG_BRK_DELAY_');
FLAG_STR_DELAY_ = get_param(SimulinkModel,'FLAG_STR_DELAY_');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Set Simulation Mode %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch FLAG_MODE_
    case 'CarSim'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function_video'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function_video'],'Commented','on');
    case 'CarSim Real-Time'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function_video'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function_video'],'Commented','on');
    case 'TruckSim'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function_video'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function_video'],'Commented','on');
    case 'TruckSim Real-Time'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'CarSim S-Function_video'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function'],'Commented','on');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'TruckSim S-Function_video'],'Commented','off');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Set Actuator Dynamics %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch FLAG_ENG_LAG_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Eng_Lag'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Eng_Lag'],'Commented','through');        
end
switch FLAG_ENG_DELAY_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Eng_Delay'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Eng_Delay'],'Commented','through');        
end
switch FLAG_MTR_LAG_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Lag_RR'],'Commented','through');      
end
switch FLAG_MTR_DELAY_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Mtr_Delay_RR'],'Commented','through');   
end
switch FLAG_BRK_LAG_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Lag_RR'],'Commented','through');     
end
switch FLAG_BRK_DELAY_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Brk_Delay_RR'],'Commented','through'); 
end
switch FLAG_STR_LAG_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Lag_RR'],'Commented','through');    
end
switch FLAG_STR_DELAY_
    case 'on'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_FL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_FR'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_RL'],'Commented','off');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_RR'],'Commented','off');
    case 'off'
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_FL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_FR'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_RL'],'Commented','through');
        set_param(['Vehicle_Dynamic_Simulator/v0.40c/MODULE::Simulation/' ...
                   'Str_Delay_RR'],'Commented','through');
end